export default [
  {
    id: 0,
    type: 'jpg',
    title: '3 Ways To Stay Awake',
    uploader: 'Hendrik Hausen',
    date: '30.12.2016',
    views: 1337,
  },
  {
    id: 1,
    type: 'jpg',
    title: '2017',
    uploader: 'Sir Hennihau',
    date: '29.12.2016',
    views: 6922,
  },
  {
    id: 2,
    type: 'jpg',
    title: 'Psychology of Color',
    uploader: 'http://www.stevenspielbergfan.com/',
    date: '20.12.2016',
    views: 2349,
  },
  {
    id: 3,
    type: 'jpg',
    title: 'Suicide',
    uploader: '@allahuakbar',
    date: '31.12.2016',
    views: 43,
  },
  {
    id: 4,
    type: 'jpg',
    title: 'Wodka',
    uploader: 'Wodka Gorbatschow',
    date: '6102.21.13',
    views: 37.5,
  },
  {
    id: 5,
    type: 'gif',
    title: 'Dog',
    uploader: 'https://www.mops.de/',
    date: '24.12.2016',
    views: 135096,
  },
  {
    id: 6,
    type: 'jpg',
    title: 'Dumbledore',
    uploader: 'Harry Potter',
    date: '05.12.5013',
    views: 9.75,
  },
];
